services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: myStore
      POSTGRES_USER: capinz
      POSTGRES_PASSWORD: capinz123
    ports:
      - "5432:5432"
    volumes:
      - ./postgresData:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
